---
title: "DDIB week 11: Data analysis"
author: "Job"
date: "1/27/2020"
output: html_document
---

# Jetzt faengt es an

## Data selection

```{r}
library(tidyverse)
library(lme4)
d <- read.csv("stex.csv")

# library(foreign)
# write.foreign(d, "stex.sav", codefile, package="SPSS")

dim(d)

d <- d %>% 
  filter(!is.na(Edu.day)) %>% 
  filter(!is.na(new_feat)) %>% 
  filter(AaA > 18) %>% 
  filter(AaA < 50)

dim(d)
```

jetzt sind weniger Observationen da

# Data analysis

```{r}
baseline_ml <- lmer(Speaking ~ Sex + AaA + LoR + 
                     Edu.day + Enroll + Edu.day:Enroll +
                     (1|C) + (1|L1),
                   data = d, REML = FALSE)
summary(baseline_ml) 

newfeat_ml <- update(baseline_ml, . ~ . + new_feat)
summary(newfeat_ml)$coef 

anova(newfeat_ml, baseline_ml)
```


# Visualization

```{r}
library(sjPlot)
p <- plot_models(newfeat_ml, show.legend = FALSE) + ylab(expression(paste("Negative and positive effects on L", italic("n"), " learning")))
p
ggsave("effects.pdf", width = 6, height = 4)
```


```{r}
adj_scores <- ranef(baseline_ml)$L1
colnames(adj_scores) <- c("Adjustment")
adj_scores$L1 <- rownames(adj_scores)
per_L1 <- d %>% 
  select(L1, morph, lex, new_feat, new_sounds, Family) %>% 
  distinct() %>% 
  left_join(adj_scores)

with(per_L1, cor(new_feat, Adjustment, use = "pairwise.complete.obs")) 

# basic scatterplot
ggplot(per_L1 , aes(x = new_feat, y = Adjustment)) + 
  geom_point() +
  stat_smooth() +
ggsave("scatter-simple.pdf", width = 6, height = 4)
	
	
# more complex scatterplot
keep <- c("German", "Swedish", "English", "Korean", "Turkish", "Spanish", "Russian", "Greek", "Tagalog", "Thai", "Finnish",
          "Somali", "Albanian", "Georgian", "Mongolian", "Norwegian", "Bengali", "Romanian", "Ukrainian")
per_L1$L1 <- as.character(per_L1$L1)
per_L1$L1v <- ""
per_L1 $L1v[per_L1 $L1 %in% keep] <- per_L1 $L1[per_L1 $L1 %in% keep]
lm_eqn <- function(m) {
  l <- list(a   = format(    coef(m)[1],  digits = 2),
            b   = format(abs(coef(m)[2]), digits = 2),
            r2  = format(     summary(m)$r.squared, digits = 2),
            r.r = format(sqrt(summary(m)$r.squared), digits = 2))
  eq <- substitute(italic(r)~"= -"~r.r,l)
  as.character(as.expression(eq));
}
library(ggrepel)
ggplot(per_L1 , aes(x = new_feat, y = Adjustment, label = L1v)) + 
  geom_point(aes(colour = Family), size = 1.5) +
  stat_smooth(aes(group = 1), method = "lm", show.legend = F) +
  xlab("New features for every new sound category not present in L1") + 
  ylab("Adjusted Dutch speaking score\n(by-L1 random intercept)") +
  geom_text_repel(aes(alpha = .5),
  				  segment.colour="black", 
  				  min.segment.length = 0.25, 
                  size = 2,
                  box.padding = unit(0.35, "lines"),
                  point.padding = unit(0.25, "lines"),
                  segment.size = 0.5,
                  force = 2,
                  max.iter = 3000,
                  segment.color = '#cccccc',
                  show.legend = F) +	
  annotate(geom = "text", x = 29, y = 33, 
           parse = T,
           label = lm_eqn(lm(Adjustment ~ new_feat, per_L1 )), 
           col = "black") + 
  scale_y_continuous(breaks = c(-20, 0, 20), limits = c(-22, 34)) +
  guides(colour = guide_legend(title = "Language\nFamily",
  							 keyheight=0.6)) + 
  theme_bw() + 
  theme(
  	legend.text = element_text(size = 6),
  	# legend.spacing.y = unit(1, 'cm'), 
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank())
ggsave("scatter-complex.pdf", width = 6, height = 4)
```